apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webapp-dev

resources:
- ../../../base/frontend

replicas:
- name: frontend
  count: 1

configMapGenerator:
- name: frontend-content
  behavior: merge
  literals:
  - index.html=|
      <!DOCTYPE html>
      <html>
      <head><title>GitOps Demo - DEV</title></head>
      <body style="background: #fff3cd;">
        <h1>🛠️ DEVELOPMENT Environment</h1>
        <p>Version: 1.0.0-dev</p>
        <p>This is the development environment!</p>
      </body>
      </html>

commonLabels:
  environment: development
  version: "1.0.0-dev"
