apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webapp-dev

resources:
- ../../../base/frontend

replicas:
- name: frontend
  count: 1

patchesStrategicMerge:
- config-patch.yaml

commonLabels:
  environment: development
  version: "1.0.0-dev"
