apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "-2"
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: postgres:13-alpine
        command: ["sh", "-c"]
        args:
        - |
          echo "Running database migrations..."
          sleep 10
          echo "Migration completed!"
      restartPolicy: Never
  backoffLimit: 3