apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
type: Opaque
stringData:
  url: "postgresql://webapp:webapp123@postgres-postgresql.webapp-data.svc.cluster.local:5432/webapp"
  username: "webapp"
  password: "webapp123"
