apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-config
  namespace: default
spec:
  encryptedData:
    api-key: AgAUKaexVZBTr5/xGBVnK5o6NEzdE7jbuYKfn10c6KjopCJqnnbkqkDKdQOJZg87Vtyr6/KsdvDMyjNQPSpS1oXN+TiAhUQKmd+UMzraTXj73Vh8cdlialexL+KrIGq433nL/NVHmC33dWzxcThaPvl3ZoP3A7bGZ8gMDcyTBiQJ0S7IV7T/QDB2sjxVrImakxU1pOfTkO/I+prNxTXTIKGtClI17D6WugIbSROholr6nWuZgoMfkBA0VsaTvNLiIEv6XXIp2D/lHtdV3jt1VKZsdUChy6jIrLk6//5dnONZcKrl6lwZRJsKMyafgH6xZYbCsMWS9G92ZqM50pWomJ1rA+kHLt9OgxBMQHJMx0aQPLzMUY5Eo1FZAwuhUE6Xf91hP/mM2nJZJDbc8M7xeedogIE4OwXx1WbjH2AtJupUqSc9YJxRXk+FtNxr9y35atbpClJDloBXbYl3B2JeKS/PShoFr4p32NP9fdgUBDcH+gSp7YbegbPIqp0FlMfUVppmZEhPhCBvWC38fNfFPRHQq0KBTnUME2m2WzIpsynQzEbRvdRLsfycrSQRGWvhsM3xqStRMGoFi+1Eg2EGem0Kubo7zfawXYH5p+Ehv+iAzMZfpRaEMOB8HGp9mYNEJ+kNosUjkdJZ3+Ff4tASEEMR8DW56Zzl+OkZ4nGEUyu1KyzywARDmdxuxpdZa6J6ZpeISTkxw3ZxblyXuH7vJsaU
    database-url: AgADcKUKYNhrgx5UstAr+5RSUuE6ss81Ne/en2sCPc4zyi9f6D0AVReyahAah6lFJgc5sX6sTLLlPwu5fzN9WmgNUUCm7zqsArzERiopSdTcUiQB9b9VMsred/5V84C/G99EkIuhD7jkqmuQYHqrWr4bF3MFk0hsjEjafZxaY6sMJoKMDrpUinPjahXeQCe3bhgstojNmJdBIkmG1l75XGslE3ReQA2eZ8Jqg87hDAYuiC4g/PcOeKVxSXUuHuNldFUdXG5/QjMirZQtdedj8ue7ZQpIUuL7K1hrCHNPTjHRWojW2FkCGr6v8Fx7fArRBbwx7LhKbShqw+UCwNWNllOQ+WozZsfaetG/hpo5mm82LDggVdvb3heEdGdeVuU/+npIIyQifk30vUBI0z22kqwJsc5+mdIMAMClIZHg7qSozXFPRnQDdQkiDk4IffJvxu7Mt90xZ0ms+zNBC6PJs7WcYZl1Ys1ANBiDWYgd+IMmBPmL6iOaRBhuW8HRONiJoRVNr2zbkYSAmqgONdoLwlpBqI20UNVCWwaYQufUaRGU5FfsZ1qQLeVLt2Kam+sDZ2MMUo3i7JsEbIn7oA1frFntbE30uzas54dSHRnIlOEWnLxBKJOoZ9bH76Tm3wasdNerAxObArZevAirGajYvyDnFjd9+Eg6Nfn1zXt6iDdagP2SidQ+/J9iQ+81uNd2rSLvXDj/OMnLrSqmUCtwh02IVva+PngZ/UX6NA9I1JOV7bgGLKzl5kmy+oNk6QvUti48JQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: api-config
      namespace: default

